uek_vod_homepage:
    path:     /
    defaults: { _controller: UekVodBundle:Default:index }

uek_vod_show_orders:
    path:     /show
    defaults: { _controller: UekVodBundle:DatabaseQuery:show }
    
film_genre:
    path:     /gatunek/{genre}
    defaults: { _controller: UekVodBundle:Default:genres }