uek_vod_homepage:
    path:     /
    defaults: { _controller: UekVodBundle:Default:index }

uek_vod_show_orders:
    path:     /show
    defaults: { _controller: UekVodBundle:DatabaseQuery:show }
    
film_genre:
    path:     /gatunek/{genre}
    defaults: { _controller: UekVodBundle:Default:genres }
    
film_name:
    path:     /movie/{id}
    defaults: { _controller: UekVodBundle:Default:names, s: 0 }
    
add_review:
    path:     /movie/{id}/review
    defaults: { _controller: UekVodBundle:Review:add }

task_success:
    path:     /movie/{id}/s
    defaults: { _controller: UekVodBundle:Default:names, s: 1 }
    
vod_cart:
    path:     /cart
    defaults: { _controller: UekVodBundle:Cart:show, orderNumber: 1 }
