uek_vod_homepage:
    path:     /
    defaults: { _controller: UekVodBundle:Default:index }

uek_vod_show_orders:
    path:     /show
    defaults: { _controller: UekVodBundle:DatabaseQuery:show }
    
film_genre:
    path:     /gatunek/{genre}
    defaults: { _controller: UekVodBundle:Default:genres }
    
film_name:
    path:     /film/{id}
    defaults: { _controller: UekVodBundle:Default:names }
    
add_review:
    path:     /film/{id}/review
    defaults: { _controller: UekVodBundle:Review:add }

task_success:
    path:     /film/{id}
    defaults: { _controller: UekVodBundle:Default:names }
    
#add_basket:
#    path:     /film/{id}/1
#    defaults: { _controller: UekVodBundle:Basket:add, orderNumber: 1 }
