uek_vod:
    resource: "@UekVodBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
  
#routing for login controller
login:
    pattern: /show/login
    defaults: {_controller: UekVodBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    defaults: {_controller: UekVodBundle:Security:logout }
